### ISSUE TITLE
bug: 同步问题——"TidGi-Desktop" 清空 "tiddler" 正文内容后，无法同步至 "TidGi-Mobile"

### ISSUE THREAD

**Issue by on-in-i** [tiddly-gittly/TidGi-Mobile#18]
### Environment 环境信息

- **操作系统**: `Windows 10 专业工作站版 22H2`
- **TidGi-Mobile**: `V0.3.5`
- **TidGi-Desktop**: `v0.8.1-prerelease6`
- **tw-mobile-sync 插件**: `0.6.4`

### Description 描述

当在 "TidGi-Desktop" 上清空某 "tiddler" 的正文内容并尝试同步时，该内容在 "TidGi-Mobile" 上未更新为清空状态。但相同操作在 "TidGi-Mobile" 上进行时，"TidGi-Desktop" 上的内容得到了同步并清空。

### Steps to Reproduce 复现方式

1. 打开 "TidGi-Desktop"，创建一个新的 "wiki"。
2. 启用 `启用HTTP API` 设置，并将 `tw-mobile-sync 插件` 更新至最新版。
3. 按照 “同步流程”，同步新 "wiki" 至 "TidGi-Mobile"。
4. 在 "TidGi-Desktop" 上添加 “新条目”，输入正文 “123”。
5. 使用 “同步流程” 将 “新条目” 同步至 "TidGi-Mobile"。
6. 尝试对 "新条目" 进行 "清空全部正文内容" 的操作并同步：
   - **第一种情况**:
     - 在 "TidGi-Desktop" 上操作，尝试同步至 "TidGi-Mobile"。
     - 结果：同步失败，"TidGi-Mobile" 上的 “新条目” 正文保持为 “123”。
   - **第二种情况**:
     - 在 "TidGi-Mobile" 上操作，尝试同步至 "TidGi-Desktop"。
     - 结果：同步成功，"TidGi-Desktop" 的 “新条目” 正文已清空。

### Additional Context 额外上下文

- 所有软件均使用的是最新版本。
- 该问题可能导致 "TidGi-Mobile" 与 "TidGi-Desktop" 的数据不同步，给用户带来困惑。

**Comment by linonetwo** [comment]
可以打开太记的 log，搜一下是不是有 `Unhandled case:`

https://github.com/tiddly-gittly/tw-mobile-sync/blob/907eb3699c393d5cdc35a166410f14b7412263df/src/tw-mobile-sync/server/TidGi-Mobile/server-sync-v1-endpoint.ts#L96-L104

就是这一行，可能有遗漏的情况

**Comment by linonetwo** [comment]
一般来说，桌面的变化是会同步了的，不过如果桌面和手机两边「在上次同步之后」都修改了同一个文件，就会以移动端为准。

一定会同步的情况是，「在上次同步之后」只有一边修改了同名的文件

**Comment by on-in-i** [comment]
```
{"function":"startNodeJSWiki","level":"info","message":"Unhandled case: 新条目 \nwhere Invalid Date > Mon Sep 11 2023 13:51:40 GMT+0800 (中国标准时间) is false {\n  created: '20230911034508587',\n  creator: 'TidGi User',\n  title: '新条目',\n  modified: '20230911055210840',\n  modifier: 'TidGi User',\n  tags: '',\n  type: 'text/vnd.tiddlywiki',\n  text: ''\n} [Object: null prototype] {\n  created: 2023-09-11T03:45:08.587Z,\n  creator: 'TidGi User',\n  title: '新条目',\n  modified: 2023-09-11T05:51:40.539Z,\n  modifier: 'TidGi User',\n  tags: [],\n  type: 'text/vnd.tiddlywiki',\n  text: '123456'\n}\n","timestamp":"2023-09-11T05:52:16.785Z"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2023-09-11T05:52:16.787Z","type":"result","uid":"2"}
```
确实是有的

**Comment by on-in-i** [comment]
> 一般来说，桌面的变化是会同步了的，不过如果桌面和手机两边「在上次同步之后」都修改了同一个文件，就会以移动端为准。
> 
> 一定会同步的情况是，「在上次同步之后」只有一边修改了同名的文件

“ 一定会同步的情况是，「在上次同步之后」只有一边修改了同名的文件”，描述的操作确实满足这个条件，只在 "TidGi-Desktop" 清空某一个“tiddler”的全部正文内容，就无法将正文空白的“tiddler”文件同步到"TidGi-Mobile"。

**Comment by linonetwo** [comment]
的确，是有逻辑有问题，之前如果传来的 text 为空就会忽略，防止删除移动端的内，但其实可能就是内容被用户主动删了。
