### ISSUE TITLE
TidGi-Mobile V0.0.4 版本中 KaTex 公式渲染问题

### ISSUE THREAD

**Issue by on-in-i** [tiddly-gittly/TidGi-Mobile#2]
**背景信息**：
- 软件：TidGi-Mobile（Android版）与 TidGi-Desktop（Windows版）
- 使用版本：
  - TidGi-Mobile：V0.0.4
  - TidGi-Desktop：v0.8.1-prerelease6
  - tw-mobile-sync 插件：0.6.0
  - KaTex 插件：5.3.0
- 所有上述版本均为最新版。

**问题描述**：

在 TidGi-Desktop 上，我有一个包含 KaTex 公式的条目。
该公式在 TidGi-Desktop 客户端上能够正常渲染（如配图一所示）,

![2023-09-06_00003](https://github.com/tiddly-gittly/TidGi-Mobile/assets/100055123/8e51477c-3c04-4b20-a480-e06abcb7e818)

并且编辑框中的 KaTex 按钮也正常显示（如配图二所示）。

![2023-09-06_00004](https://github.com/tiddly-gittly/TidGi-Mobile/assets/100055123/0719d965-05bb-4d8a-b294-4c5b0710c51d)

但当我使用 tw-mobile-sync 插件同步该条目到 TidGi-Mobile 后，遇到以下问题：
1. KaTex 公式在 TidGi-Mobile 上无法正常渲染，并显示报错：`ParseError:KaTeX parse error:KaTeX doesn't work in quirks mode.`（如配图三所示）。
<img width="543" alt="Screenshot_2023_0906_225933" src="https://github.com/tiddly-gittly/TidGi-Mobile/assets/100055123/2d705f1f-f5bb-4d74-8bba-a65a4277f185">

2. 编辑框中的 KaTex 按钮也无法正常显示，并显示同样的报错信息`ParseError:KaTeX parse error:KaTeX doesn't work in quirks mode.`（如配图四所示）。
<img width="543" alt="Screenshot_2023_0906_230022" src="https://github.com/tiddly-gittly/TidGi-Mobile/assets/100055123/8ae214f5-b19c-4086-a4a6-9f08f54efef5">

**Comment by linonetwo** [comment]
很好的反馈，这个在 v0.1.0 版本里应该修复了，已发布，QQ 群文件也有，来试试吧。

**Comment by linonetwo** [comment]
之前是因为没初始化好，进了这个模式 https://developer.mozilla.org/zh-CN/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
