### ISSUE TITLE
Sync error while processing load of '白色夹竹桃.png': Error: Tiddler "白色夹竹桃.png" is not synced yet.

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Mobile#20]
### Environment 环境信息

v0.3.5

### Description 描述

syncer-browser-tidgi-mobile-fs - 2023年09月11日 17:48
Sync error while processing load of '白色夹竹桃.png': Error: Tiddler "白色夹竹桃.png" is not synced yet.

### Steps to Reproduce 复现方式

同步成功后，打开引用图片条目的条目即可产生该问题。

例如`[img[图片]]`

**Comment by linonetwo** [comment]
改进了一下消息提示，这时候应该连上服务器就能同步过来了，如果没连上可以长按列表里的wiki打开工作区设置，在服务器列表里看看连没连上，没连上点一下同步会尝试连接。

**Comment by Zacharia2** [comment]
okk。谢谢，辛苦啦 coffee
