### ISSUE TITLE
feature: 在tiddler页面查找并高亮特定文本

### ISSUE THREAD

**Issue by HushHorizon** [tiddly-gittly/TidGi-Mobile#26]
### Description 描述

<img src="https://github.com/tiddly-gittly/TidGi-Mobile/assets/100055123/74336004-557b-4ed4-82a3-4ea5627b6400" width="300">

-------

图片为安卓edge浏览器的“在页面上查找”功能，可参考此功能。

- 功能描述
    - 在已经打开的tiddler页面中查找特定文本，高亮特定文本，同时跳转到特定文本位置，

### Additional Context 额外上下文

找到的各种搜索高亮插件都只能通过键盘中的"Ctrl+F"或"Ctrl+G"等快捷键使用，不知该如何在"TidGi-Mobile"中实现“在页面上查找”功能。

如果在"TidGi-Mobile"中已经可以通过特定方法在已经打开的tiddler页面中实现“在页面上查找”功能，烦请告知。

**Comment by linonetwo** [comment]
有相关教程 https://levelup.gitconnected.com/unlocking-the-impossible-search-keywords-within-webview-in-react-native-6d91c8f57aba

感兴趣可以配合 ChatGPT 提个 PR

**Comment by on-in-i** [comment]
> 有相关教程 https://levelup.gitconnected.com/unlocking-the-impossible-search-keywords-within-webview-in-react-native-6d91c8f57aba
> 
> 感兴趣可以配合 ChatGPT 提个 PR

哈哈，那加入任务列表，尝试一下。

**Comment by HushHorizon** [comment]
在搜索相关信息的过程中，发现了一个已经实现这个功能的 tiddlywiki 插件，这是插件网址 `https://bimlas.gitlab.io/tw5-highlight-searched-text/`。

经测试，此插件可以在单文件 HTML 上顺利使用，但是在 `TidGi-Desktop` 上无法使用，在拖入插件后便会报错，已提交相关 issue`https://github.com/tiddly-gittly/TidGi-Desktop/issues/477`，暂且不知道该插件在 `TidGi-Mobilei` 上能否成功使用，因为 `TidGi-Mobile` 现在只能从 `TidGi-Desktop` 导入并同步 wiki。

现在的情况：等待 issue`https://github.com/tiddly-gittly/TidGi-Desktop/issues/477` 的修复，在此之后，测试该插件能否在 `TidGi-Mobile` 上顺利使用。

**Comment by HushHorizon** [comment]
现在觉得在手机上用浏览器查看单文件HTML还是比较方便的，临时笔记就记在手机txt文档中，再统一整合进电脑里。由于需求发生变化，故关闭此issue。
