### ISSUE TITLE
bug: 同步功能反向优化(?

### ISSUE THREAD

**Issue by HushHorizon** [tiddly-gittly/TidGi-Mobile#27]
### Environment 环境信息

- **操作系统**: `Windows 10 专业工作站版 22H2`
- **TidGi-Mobile**: `V0.4.3`
- **TidGi-Desktop**: `v0.8.1-prerelease6`
- **tw-mobile-sync 插件**: `0.6.4`

### Description 描述

- 两种需要同步的操作
    - "重命名条目"
    - "删除条目"
- 两个版本
    - V0.4.2
    - V0.4.3
- 两种同步方向
    - 从电脑端到手机端
    - 从手机端到电脑端

共有八种同步情况，“八种情况”详情见“复现方式”。

### Steps to Reproduce 复现方式

![output](https://github.com/tiddly-gittly/TidGi-Mobile/assets/100055123/8e3d31a1-06de-47f2-938a-f75e89a23eb9)

### Additional Context 额外上下文

复现方式皆为“手动测试”，若发现其存在问题请指出。

鉴于同步功能目的是：把“电脑端不在身边时的手机编辑操作”成功同步到电脑端。

所以，仅关注于“把手机端操作同步到电脑端”，V0.4.2 TidGi-Mobile 可以成功同步"重命名条目"和"删除条目"这两个操作，但 V0.4.3 TidGi-Mobile 不能成功同步"重命名条目"和"删除条目"这两个操作。

希望在后续版本中，能重新实现---对于“把手机端操作同步到电脑端”，可以成功同步"重命名条目"和"删除条目"这两个操作。

若其优化有特殊原因，不能重新实现上述同步功能，也请告知。

**Comment by linonetwo** [comment]
感谢测试，可能是删除操作没被电脑端用上，这个有空再看。

反正目前新增的都没问题，能正常保存到电脑端就好，不影响日常速记。别的暂时可以通过删除了重新创建来解决。

**Comment by king0billy** [comment]
电脑手机分别编辑同一个条目的内容然后再点手机上的同步。结果没有处理冲突或者增量备份，电脑和手机这个条目显示不同的内容 。这算bug还是无法实现的功能

**Comment by linonetwo** [comment]
应该是会以手机为准，覆盖掉电脑的，我也不确定，具体得看 https://github.com/tiddly-gittly/tw-mobile-sync 里的逻辑

**Comment by HushHorizon** [comment]
现在觉得在手机上用浏览器查看单文件HTML还是比较方便的，临时笔记就记在手机txt文档中，再统一整合进电脑里。由于需求发生变化，故关闭此issue。

**Comment by king0billy** [comment]
安卓手机用termux+syncthing 同步挺方便的我用了两个月了

**Comment by king0billy** [comment]
> 现在觉得在手机上用浏览器查看单文件HTML还是比较方便的，临时笔记就记在手机txt文档中，再统一整合进电脑里。由于需求发生变化，故关闭此issue。

安卓手机用termux+syncthing 同步挺方便的 也不会出现你上述的问题 我用了两个月了

**Comment by HushHorizon** [comment]
> > 现在觉得在手机上用浏览器查看单文件HTML还是比较方便的，临时笔记就记在手机txt文档中，再统一整合进电脑里。由于需求发生变化，故关闭此issue。
> 
> 安卓手机用termux+syncthing 同步挺方便的 也不会出现你上述的问题 我用了两个月了

感谢建议，有需要的话会去尝试一下。
