### ISSUE TITLE
feature: Expo似乎支持IOS系统的打包

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Mobile#28]
### Description 描述

一个小想法：Expo似乎支持IOS系统的打包，这样IOS与IPad也跟随安卓一块覆盖了。

弥补了IOS与IPad的短板与不足。

**Comment by linonetwo** [comment]
我可以上个收费包回收成本，但是首先开发者账号就无法通过注册，现在个人没法轻易注册了

**Comment by Zacharia2** [comment]
嗯嗯，不通过商店似乎有签名就可以安装，使用GitHub提供安装包，以这种方式提供安装也不错。但签名收费，不过也看到可以免费签名的工具和方法安装。
