### ISSUE TITLE
同步后，过一段事件同步功能失效。

### ISSUE THREAD

**Issue by Unword** [tiddly-gittly/TidGi-Mobile#30]
手机是mimu14，电脑是最新win10，同一网络下。
为什么有时候刚开始同步没问题，后来不知道为啥，就无法同步了，手机和电脑的地址没有做任何改动，两个客户端和插件都是最新的。某一天后就突然不行了，两个客户端都打开的情况下，点击**wiki立即同步云端**那个按钮变成了**x立即同步云端**，点一下，转一下，但是并没有同步成功。

**Comment by linonetwo** [comment]
说明没连上，可能不在一个wifi下

**Comment by Unword** [comment]
发现怎么解决了，是这样的，删除重新添加一次就可以了。
可能重启路由、光猫可能会导致这个问题。

**Comment by linonetwo** [comment]
长按可以编辑，里面可以再次扫码
