### ISSUE TITLE
bug: 手机端中的wiki扫码缺少权限，不可用

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Mobile#4]
### Environment 环境信息

安卓 v0.3.0

### Steps to Reproduce 复现方式

进入wiki后，点击mobilesync，点击扫描二维码，出现 unable to access video stream （please make sure you have a webcam enabled）

**Comment by linonetwo** [comment]
这是个问题，不过手机里的 mobilesync 插件已经用不着了，现在是列表页长按 wiki 有个同步

![](https://github.com/tiddly-gittly/TidGi-Mobile/raw/master/docs/images/Screenshots/Screenshot-Edit-Wiki.jpg)

Sync to cloud

我之后让 wiki 里的按钮也改成调用这个

**Comment by linonetwo** [comment]
目前在 mobile sync 插件里去掉了这些功能，都用app原生功能来扫了。
