### ISSUE TITLE
华为鸿蒙系统打不开应用

### ISSUE THREAD

**Issue by ctp128** [tiddly-gittly/TidGi-Mobile#57]
### Description 描述

应该是扫码后直接能同步

### Steps to Reproduce 复现方式

在桌面端新建一个 新的wiki，然后把所有的插件更新后，再使用移动端TidGi的扫描二维码开关扫桌面端的二维码后可进入导入wiki，然后当进入wiki后就显示一个空白页面。无任何内容，手机是Android13版本，

- TidGi版本是0.7.3。
- 桌面端启用API

**Comment by linonetwo** [comment]
这就不清楚了，我刚拿最新版的 太记桌面版  v0.9.3 创建 wiki 试了一下，可以正常导入

**Comment by zhoukun222408** [comment]
Environment 环境信息
桌面端版本：tidgi(win32)0.9.3
操作系统：win10专业版
安卓版本：0.7.3
手机系统：鸿蒙4.0
手机信号：Mate30 5G

Description 描述
安卓手机端扫码PC端二维码，同步成功后，打开后是空白页

Steps to Reproduce 复现方式
桌面端新建库，然后把同步插件更新，打开服务器API设置，再使用安卓端的扫描桌面端的二维码导入，成功后依然是显示空白页。

另外发现安卓端用模板本地新建wili居然也是空白页，并且要申请麦克风使用授权

**Comment by linonetwo** [comment]
@zhoukun222408 可以用 usb 连上电脑，然后用 Edge 打开 edge://inspect/#devices 看看

![图片](https://github.com/tiddly-gittly/TidGi-Mobile/assets/3746270/1d76bf76-2b78-4983-992e-0d0a252bcbb7)

看看这里打开有没有报错信息

**Comment by linonetwo** [comment]
@zhoukun222408 @ctp128 有用 CPL 更新所有插件吗？

**Comment by linonetwo** [comment]
据说在华为手机上 webview 不加载，但开启开发者模式 usb调试+连接数据线后能加载

不然就是
![07257ae4c15367294c61e4d589c3e610](https://github.com/tiddly-gittly/TidGi-Mobile/assets/3746270/df5067c9-13de-48a2-8584-1e1a69cafbc6)

**Comment by linonetwo** [comment]
据传在系统设置里打开应用的访问存储权限就可以了

![0b739f836a675bf51389603bce4abd12](https://github.com/tiddly-gittly/TidGi-Mobile/assets/3746270/9116de29-b460-4225-b87f-7d49e8d260e5)

华为居然不会主动提示用户，非常不人性化。

**Comment by linonetwo** [comment]
华为的 webview 有bug，加载速度很慢，明显慢于其他机型，新版会等待它一下。
