### ISSUE TITLE
发现了报错信息

### ISSUE THREAD

**Issue by zhoukun222408** [tiddly-gittly/TidGi-Mobile#58]
![image](https://user-images.githubusercontent.com/161402284/309546032-3514c73d-21bd-4f9a-bcb7-052a977c012b.png)

![image](https://user-images.githubusercontent.com/161402284/309546013-2011b7dc-92df-42c1-a8b8-1a98cc1dcec9.png)
             

@zhoukun222408 可以用 usb 连上电脑，然后用 Edge 打开 edge://inspect/#devices 看看

![图片](https://github.com/tiddly-gittly/TidGi-Mobile/assets/3746270/1d76bf76-2b78-4983-992e-0d0a252bcbb7)

看看这里打开有没有报错信息，点 inspect ，然后里面的 console 看看有没有报错

![图片](https://github.com/tiddly-gittly/TidGi-Mobile/assets/3746270/22ff8fc5-bacb-4c7b-97e8-b774a1f25c63)

_Originally posted by @linonetwo in https://github.com/tiddly-gittly/TidGi-Mobile/issues/57#issuecomment-1975124962_

**Comment by linonetwo** [comment]
@zhoukun222408 你的图片上传失败了，看不到

**Comment by zhoukun222408** [comment]
网络不行
Failed to load resource: the server responded with 192.168.2.6/:1 a status of 404 (Not Found)







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tiddly-gittly/TidGi-Mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月3日(星期天) 晚上7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tiddly-gittly/TidGi-Mobile] 发现了报错信息 (Issue #58)





 
@zhoukun222408 你的图片上传失败了，看不到

**Comment by linonetwo** [comment]
192.168.2.6/:1 这个地址不对吧，这是哪里的，你把截图发上来吧
