### ISSUE TITLE
Android bug (?) : add workspace => create from template does nothing

### ISSUE THREAD

**Issue by Telumire** [tiddly-gittly/TidGi-Mobile#63]
### Environment 环境信息

Android 13, fairphone 4, app version 0.7.5

### Description 描述

The button "create from template" in "Add Workspace" does not seem to work (or is missing contextual hints)

### Steps to Reproduce 复现方式

https://github.com/tiddly-gittly/TidGi-Mobile/assets/31185220/9e6484df-fa3d-417f-89ea-d0b6b0ac58e4

**Comment by Telumire** [comment]
If this behavior is expected (maybe the user need to add a url to a template first ?), then the button should be either hidden, or a message should appear to explain why nothing is happening (in my opinion).

**Comment by Telumire** [comment]
After using the button "Remove All Wiki Data", I now see two templates: "Tiddlywiki XP Template" and "TidGi Default Template"

**Comment by linonetwo** [comment]
Thanks for reporting, that list is loaded from a wiki with filter expression ( from tag https://tidgi.fun/#WikiTemplates ), and sometimes maybe too many request cause it slow. I will add a loading indicator to it.
