### ISSUE TITLE
feature: allow user to re-download the help wiki after the button "remove all wiki data" was pressed

### ISSUE THREAD

**Issue by Telumire** [tiddly-gittly/TidGi-Mobile#64]
### Description 描述

In "Preference", there is a button in the developer tools section to "Remove All Wiki Data". Currently there is no way to download the default help wiki, maybe it should appear as a template ?

**Comment by linonetwo** [comment]
I think the help wiki is in "Add webpage shortcut" (when it is loaded), so this is influenced by #63
